version: '3.4'

services:
  rabbitmq:
    hostname: 'poc-rabbitmq'
    container_name: 'rabbitmq'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

  poc.opentelemetry.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - PATH_BASE=/poc.opentelemetry.api
      - RABBIT_HOSTNAME=rabbitmq
    restart: on-failure
    ports:
      - "5000:80"
      - "5001:443"

  poc.opentelemetry.workerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - PATH_BASE=/poc.opentelemetry.workerservice
      - RABBIT_HOSTNAME=rabbitmq
    restart: on-failure
    ports:
      - "6000:80"
      - "6001:443"
