version: '3.7'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'

  zipkin:
    image: openzipkin/zipkin
    ports: 
      - 9411:9411
  
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - 16686:16686

  poc.opentelemetry.api:
    image: ${DOCKER_REGISTRY-}opentelemetryapi
    build:
      context: .
      dockerfile: POC.OpenTelemetry.API/Dockerfile
    depends_on:
      - rabbitmq

  poc.opentelemetry.workerservice:
    image: ${DOCKER_REGISTRY-}opentelemetryworkerservice
    build:
      context: .
      dockerfile: POC.OpenTelemetry.WorkerService/Dockerfile
    depends_on:
      - rabbitmq

