version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: rabbitmq

  zipkin1:
    image: openzipkin/zipkin
    container_name: zipkin
    ports: 
      - 9411:9411
  
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - 16686:16686

  sql-server:
    image: microsoft/mssql-server-linux:latest    
    container_name: sqlServer
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data

  poc.opentelemetry.api:
    image: ${DOCKER_REGISTRY-}opentelemetryapi
    build:
      context: .
      dockerfile: POC.OpenTelemetry.API/Dockerfile
    depends_on:
      - rabbitmq
      - sql-server
      - zipkin1
      - jaeger

  poc.opentelemetry.workerservice:
    image: ${DOCKER_REGISTRY-}opentelemetryworkerservice
    build:
      context: .
      dockerfile: POC.OpenTelemetry.WorkerService/Dockerfile
    depends_on:
      - rabbitmq
      - zipkin1
      - jaeger

volumes:
  mssql-server-linux-data: