version: '3.4'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'

  poc.opentelemetry.api:
    image: ${DOCKER_REGISTRY-}opentelemetryapi
    build:
      context: .
      dockerfile: POC.OpenTelemetry.API/Dockerfile
    depends_on:
      - rabbitmq

  poc.opentelemetry.workerservice:
    image: ${DOCKER_REGISTRY-}opentelemetryworkerservice
    build:
      context: .
      dockerfile: POC.OpenTelemetry.WorkerService/Dockerfile
    depends_on:
      - rabbitmq
