version: '3.4'

services:
  poc.opentelemetry.api:
    image: ${DOCKER_REGISTRY-}opentelemetryapi
    build:
      context: .
      dockerfile: POC.OpenTelemetry.API/Dockerfile

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - network

networks:
  # Network default settings are fine.
  network: {}
