version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
  
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports: 
      - 9411:9411
  
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - 16686:16686

  sql-server:
    image: microsoft/mssql-server-linux:latest    
    container_name: sqlServer
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data

  poc.opentelemetry.grpc:
    image: ${DOCKER_REGISTRY-}pocopentelemetrygrpc
    build:
      context: .
      dockerfile: POC.OpenTelemetry.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ZIPKIN_HOSTNAME=zipkin
      - JAEGER_HOSTNAME=jaeger
    ports:
      - "7000:80"

  poc.opentelemetry.api:
    image: ${DOCKER_REGISTRY-}opentelemetryapi
    container_name: OpenTelemetry-API
    build:
      context: .
      dockerfile: POC.OpenTelemetry.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - ZIPKIN_HOSTNAME=zipkin
      - JAEGER_HOSTNAME=jaeger
    ports:
      - "5000:80"
      - "5001:443"
    restart: on-failure
    depends_on:
      - rabbitmq
      - sql-server
      - zipkin
      - jaeger

  poc.opentelemetry.worker:
    image: ${DOCKER_REGISTRY-}opentelemetryworker
    build:
      context: .
      dockerfile: POC.OpenTelemetry.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServiceHost=http://poc.opentelemetry.grpc
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - ZIPKIN_HOSTNAME=zipkin
      - JAEGER_HOSTNAME=jaeger
    depends_on:
      - rabbitmq
      - zipkin
      - jaeger
      - poc.opentelemetry.grpc
    restart: on-failure
    ports:
      - "6000:80"
      - "6001:443"
  
volumes:
  mssql-server-linux-data: